services:
  api-app:
    build:
      context: .
      dockerfile: Dockerfile-app
    networks:
      - app-network
    env_file:
      - .env
    image: api-app
  
  nginx:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-serve
    environment:
      - PORT=80
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api-app
    networks:
      - app-network
    volumes:
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt

networks:
  app-network:
    driver: bridge