name: Test Deploy to EC2

on:
  push:
    branches: [ "dev" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SSH and Setup
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. Clean and Prepare directory
            sudo rm -rf /home/ubuntu/api
            mkdir -p /home/ubuntu/api
            cd /home/ubuntu/api

            # 2. Clone fresh (HTTPS is easier for this test)
            git clone -b dev https://github.com/gmenchaca/git-backend-2.git .

            # 3. Handle the .env file
            # If you manually created a .env on the EC2, 
            # the 'rm -rf' above just deleted it. 
            # Let's recreate a basic one or move it from a safe spot:
            echo "${{ secrets.DOT_ENV_PRODUCTION }}" > .env

            # 4. Build and Run (Production)
            docker compose up -d --build